version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=votre_secret_jwt
      - JWT_EXPIRES_IN=24h
      - FRONTEND_URL=http://localhost:3001
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    networks:
      - supchat-network

  web:
    build:
      context: ./web/supchat-web
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - VUE_APP_API_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - supchat-network

networks:
  supchat-network:
    driver: bridge